name: voice_diagnosis_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - librosa
  - mysql-connector-python
  - pip:
      - -r backend/requirements.txt 