"""init

Revision ID: 1be8ff42b15b
Revises: 
Create Date: 2025-05-23 08:12:04.641775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1be8ff42b15b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('voice_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('voice_file_path', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('mfcc_1', sa.Float(), nullable=True),
    sa.Column('mfcc_2', sa.Float(), nullable=True),
    sa.Column('mfcc_3', sa.Float(), nullable=True),
    sa.Column('mfcc_4', sa.Float(), nullable=True),
    sa.Column('mfcc_5', sa.Float(), nullable=True),
    sa.Column('mfcc_6', sa.Float(), nullable=True),
    sa.Column('mfcc_7', sa.Float(), nullable=True),
    sa.Column('mfcc_8', sa.Float(), nullable=True),
    sa.Column('mfcc_9', sa.Float(), nullable=True),
    sa.Column('mfcc_10', sa.Float(), nullable=True),
    sa.Column('mfcc_11', sa.Float(), nullable=True),
    sa.Column('mfcc_12', sa.Float(), nullable=True),
    sa.Column('mfcc_13', sa.Float(), nullable=True),
    sa.Column('delta_1', sa.Float(), nullable=True),
    sa.Column('delta_2', sa.Float(), nullable=True),
    sa.Column('delta_3', sa.Float(), nullable=True),
    sa.Column('delta_4', sa.Float(), nullable=True),
    sa.Column('delta_5', sa.Float(), nullable=True),
    sa.Column('delta_6', sa.Float(), nullable=True),
    sa.Column('delta_7', sa.Float(), nullable=True),
    sa.Column('delta_8', sa.Float(), nullable=True),
    sa.Column('delta_9', sa.Float(), nullable=True),
    sa.Column('delta_10', sa.Float(), nullable=True),
    sa.Column('delta_11', sa.Float(), nullable=True),
    sa.Column('delta_12', sa.Float(), nullable=True),
    sa.Column('delta_13', sa.Float(), nullable=True),
    sa.Column('delta2_1', sa.Float(), nullable=True),
    sa.Column('delta2_2', sa.Float(), nullable=True),
    sa.Column('delta2_3', sa.Float(), nullable=True),
    sa.Column('delta2_4', sa.Float(), nullable=True),
    sa.Column('delta2_5', sa.Float(), nullable=True),
    sa.Column('delta2_6', sa.Float(), nullable=True),
    sa.Column('delta2_7', sa.Float(), nullable=True),
    sa.Column('delta2_8', sa.Float(), nullable=True),
    sa.Column('delta2_9', sa.Float(), nullable=True),
    sa.Column('delta2_10', sa.Float(), nullable=True),
    sa.Column('delta2_11', sa.Float(), nullable=True),
    sa.Column('delta2_12', sa.Float(), nullable=True),
    sa.Column('delta2_13', sa.Float(), nullable=True),
    sa.Column('chroma_1', sa.Float(), nullable=True),
    sa.Column('chroma_2', sa.Float(), nullable=True),
    sa.Column('chroma_3', sa.Float(), nullable=True),
    sa.Column('chroma_4', sa.Float(), nullable=True),
    sa.Column('chroma_5', sa.Float(), nullable=True),
    sa.Column('chroma_6', sa.Float(), nullable=True),
    sa.Column('chroma_7', sa.Float(), nullable=True),
    sa.Column('chroma_8', sa.Float(), nullable=True),
    sa.Column('chroma_9', sa.Float(), nullable=True),
    sa.Column('chroma_10', sa.Float(), nullable=True),
    sa.Column('chroma_11', sa.Float(), nullable=True),
    sa.Column('chroma_12', sa.Float(), nullable=True),
    sa.Column('log_mel', sa.Text(), nullable=True),
    sa.Column('contrast', sa.Float(), nullable=True),
    sa.Column('tonnetz_1', sa.Float(), nullable=True),
    sa.Column('tonnetz_2', sa.Float(), nullable=True),
    sa.Column('tonnetz_3', sa.Float(), nullable=True),
    sa.Column('tonnetz_4', sa.Float(), nullable=True),
    sa.Column('tonnetz_5', sa.Float(), nullable=True),
    sa.Column('tonnetz_6', sa.Float(), nullable=True),
    sa.Column('rms', sa.Float(), nullable=True),
    sa.Column('zcr', sa.Float(), nullable=True),
    sa.Column('bandwidth', sa.Float(), nullable=True),
    sa.Column('centroid', sa.Float(), nullable=True),
    sa.Column('rolloff', sa.Float(), nullable=True),
    sa.Column('model_prediction', sa.String(length=100), nullable=True),
    sa.Column('model_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_metrics_id'), 'voice_metrics', ['id'], unique=False)
    op.create_table('diagnosis_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('metrics_id', sa.Integer(), nullable=True),
    sa.Column('session_time', sa.DateTime(), nullable=True),
    sa.Column('llm_suggestion', sa.Text(), nullable=True),
    sa.Column('llm_processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['metrics_id'], ['voice_metrics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metrics_id')
    )
    op.create_index(op.f('ix_diagnosis_sessions_id'), 'diagnosis_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnosis_sessions_id'), table_name='diagnosis_sessions')
    op.drop_table('diagnosis_sessions')
    op.drop_index(op.f('ix_voice_metrics_id'), table_name='voice_metrics')
    op.drop_table('voice_metrics')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
