"""update_relationship_names

Revision ID: 1f96afcc6566
Revises: 443a6ca99e5b
Create Date: 2024-03-21 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f96afcc6566'
down_revision: Union[str, None] = '443a6ca99e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnosis_sessions', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('diagnosis_sessions', sa.Column('analysis_progress', sa.Integer(), nullable=True))
    op.add_column('diagnosis_sessions', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnosis_sessions', 'error_message')
    op.drop_column('diagnosis_sessions', 'analysis_progress')
    op.drop_column('diagnosis_sessions', 'status')
    # ### end Alembic commands ###
